extends SceneTree

func _initialize() -> void:
	call_deferred("_run")

func _run() -> void:
	assert(ClassDB.class_exists("VextoriaExplorerTree"), "native Explorer control is missing")
	var source := Node.new()
	source.name = "Workspace"
	root.add_child(source)
	var explorer: Tree = ClassDB.instantiate("VextoriaExplorerTree")
	root.add_child(explorer)
	explorer.call("set_source_root", source)
	var source_item: TreeItem = explorer.call("get_item_for_node", source)
	assert(source_item != null and source_item.get_text(0) == "Workspace")

	var model: Node3D = ClassDB.instantiate("Model")
	model.name = "House"
	model.set_meta("_vextoria_instance", true)
	source.add_child(model)
	var folder: Node = ClassDB.instantiate("Folder")
	folder.name = "Door Group"
	folder.set_meta("_vextoria_instance", true)
	model.add_child(folder)
	var implementation := Node.new()
	implementation.name = "Implementation"
	folder.add_child(implementation)
	var part: RigidBody3D = ClassDB.instantiate("Part")
	part.name = "Door"
	part.set_meta("_vextoria_instance", true)
	implementation.add_child(part)
	var model_item: TreeItem = explorer.call("get_item_for_node", model)
	var folder_item: TreeItem = explorer.call("get_item_for_node", folder)
	var part_item: TreeItem = explorer.call("get_item_for_node", part)
	assert(model_item.get_parent() == source_item, "Model is not under Workspace")
	assert(folder_item.get_parent() == model_item, "Folder is not under Model")
	assert(part_item.get_parent() == folder_item, "Part must skip unmarked implementation Node")
	assert(explorer.call("get_item_for_node", implementation) == null, "implementation Node leaked into Explorer")
	assert(part_item.get_child_count() == 0, "native Part internals leaked into Explorer")
	assert(explorer.call("get_node_for_item", part_item) == part, "item identity did not resolve to native Part")
	var excluded := Node.new()
	excluded.set_meta("_vextoria_instance", true)
	excluded.set_meta("_vextoria_explorer_excluded", true)
	source.add_child(excluded)
	var excluded_child := Node.new()
	excluded_child.set_meta("_vextoria_instance", true)
	excluded.add_child(excluded_child)
	assert(explorer.call("get_item_for_node", excluded) == null, "excluded node leaked into Explorer")
	assert(explorer.call("get_item_for_node", excluded_child) == null, "excluded descendant leaked into Explorer")

	part.name = "Red Door"
	assert(part_item.get_text(0) == "Red Door", "native rename was not reflected")
	var second: Node3D = ClassDB.instantiate("Model")
	second.name = "Other House"
	second.set_meta("_vextoria_instance", true)
	source.add_child(second)
	folder.reparent(second, true)
	var moved_item: TreeItem = explorer.call("get_item_for_node", folder)
	assert(moved_item.get_parent() == explorer.call("get_item_for_node", second), "reparent did not follow SceneTree")
	assert(explorer.call("get_item_for_node", part) != null, "nested Part vanished during reparent")
	source.move_child(second, 0)
	await process_frame
	assert(source_item.get_first_child() == explorer.call("get_item_for_node", second), "native order did not follow SceneTree")
	folder.free()
	assert(not is_instance_valid(moved_item), "removed Folder item remained in Explorer")
	source.free()
	assert(explorer.call("get_source_root") == null, "freed source root remained bound")
	var detached := Node.new()
	explorer.call("set_source_root", detached)
	var late_child := Node.new()
	late_child.set_meta("_vextoria_instance", true)
	detached.add_child(late_child)
	assert(explorer.call("get_item_for_node", late_child) == null, "detached node should await explicit admission")
	assert(explorer.call("ensure_item_for_node", late_child) != null, "detached Creator world cannot admit a new item")
	var pending_parent := Node.new()
	pending_parent.set_meta("_vextoria_instance", true)
	detached.add_child(pending_parent)
	var pending_child := Node.new()
	pending_child.set_meta("_vextoria_instance", true)
	pending_parent.add_child(pending_child)
	var pending_child_item: TreeItem = explorer.call("ensure_item_for_node", pending_child)
	assert(pending_child_item.get_parent() == explorer.call("get_item_for_node", pending_parent), "out-of-order admission lost the native parent")
	explorer.call("set_source_root", null)
	detached.free()
	explorer.free()
	print("VEXTORIA_NATIVE_EXPLORER_PASS: hierarchy, identity, rename, reparent, order, removal")
	quit(0)
